/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataDisplayBottom.java
 *
 * Created on 30.04.2011, 11:16:24
 */
package gui;

import javax.swing.JFrame;

/**
 *
 * @author Moe
 */
public class DataDisplayBottom extends javax.swing.JPanel {
    private float value;
    
    public DataDisplayBottom() {
        initComponents();
    }

    public DataDisplayBottom setValue(float value) {
        if (value == this.value) {
            showSameLabel();
        } else if (value > this.value) {
            showUpLabel();
        } else {
            showDownLabel();
        }
        
        this.value = value;
        updateValueLabel();
        
        return this;        
    }
    
    private void showSameLabel() {
        upLabel.setVisible(false);
        downLabel.setVisible(false);
        sameLabel.setVisible(true);
    }

    private void showUpLabel() {
        upLabel.setVisible(true);
        downLabel.setVisible(false);
        sameLabel.setVisible(false);
    }

    private void showDownLabel() {
        upLabel.setVisible(false);
        downLabel.setVisible(true);
        sameLabel.setVisible(false);
    }

    private void updateValueLabel() {
        valueLabel.setText(Float.toString(this.value));
    }    
    
    public DataDisplayBottom setUnit(String unit) {
        unitLabel.setText(unit);
        return this;
    }
    
    public DataDisplayBottom setCaption(String caption) {
        captionLabel.setText(caption);
        return this;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        captionLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        valueLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        downLabel = new javax.swing.JLabel();
        sameLabel = new javax.swing.JLabel();
        upLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.BorderLayout());

        captionLabel.setBackground(new java.awt.Color(0, 0, 0));
        captionLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        captionLabel.setForeground(new java.awt.Color(51, 204, 0));
        captionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        captionLabel.setText("Vasoconstrictor");
        add(captionLabel, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 204, 0));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(51, 204, 0));
        valueLabel.setText("0,00");
        jPanel1.add(valueLabel);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.BorderLayout());

        downLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/down.png"))); // NOI18N
        jPanel3.add(downLabel, java.awt.BorderLayout.PAGE_END);

        sameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/same.png"))); // NOI18N
        jPanel3.add(sameLabel, java.awt.BorderLayout.CENTER);

        upLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/up.png"))); // NOI18N
        jPanel3.add(upLabel, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        unitLabel.setBackground(new java.awt.Color(0, 0, 0));
        unitLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        unitLabel.setForeground(new java.awt.Color(51, 204, 0));
        unitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unitLabel.setText("kg / h / m²");
        add(unitLabel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel captionLabel;
    private javax.swing.JLabel downLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel sameLabel;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JLabel upLabel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    public static void main(String... str){
        
        JFrame frame = new JFrame("GUI Test");
        frame.setSize(800, 200);
        frame.setResizable(true);
        
        DataDisplayBottom ddl = new DataDisplayBottom();        
        ddl.setCaption("Boa constrictor").setUnit("km/h/m²").setValue(12.7f);
        frame.getContentPane().add(ddl);
        
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    } 
}
